gpu-viv: fix EULA checksum var name
Changed FSL_EULA_CHKSUM var name to FSL_EULA_FILE_MD5SUM.

This change fixes this error:
ERROR: gpu-viv-bin-s32v2xx-1_6.4.0-r0 do_populate_lic: QA Issue: gpu-viv-bin-s32v2xx: The LIC_FILES_CHKSUM does not match for file:///images/hpcsom/sources/meta-alb/EULA;md5=228c72f2a91452b8a03c4cab30f30ef9
gpu-viv-bin-s32v2xx: The new md5 checksum is ab61cab9599935bfe9f700405ef00f28
gpu-viv-bin-s32v2xx: Here is the selected license text:
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
LA_OPT_BASE_LICENSE v24 May 2018

IMPORTANT.  Read the following NXP Software License Agreement ("Agreement")
completely.    By selecting the "I Accept" button at the end of this page, you
indicate that you accept the terms of the Agreement and you acknowledge that
you have the authority, for yourself or on behalf of your company, to bind your
company to these terms.  You may then download or install the file.
...

Texas Instruments
Your use of Texas Instruments Inc. WiLink8 Licensed Software is restricted to
NXP SoC based systems that include a compatible connectivity device
manufactured by TI.
Vivante
Distribution of Vivante software must be a part of, or embedded within,
Authorized Systems that include a Vivante Graphics Processing Unit.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gpu-viv-bin-s32v2xx: Check if the license information has changed in /images/hpcsom/sources/meta-alb/EULA to verify that the LICENSE value "Proprietary" remains valid [license-checksum]
ERROR: gpu-viv-bin-s32v2xx-1_6.4.0-r0 do_populate_lic: Fatal QA errors found, failing task.
ERROR: Logfile of failure stored in: /images/hpcsom/build_s32v234hpcsom/tmp/work/aarch64-fsl-linux/gpu-viv-bin-s32v2xx/1_6.4.0-r0/temp/log.do_populate_lic.813671
ERROR: Task (/images/hpcsom/sources/meta-alb/recipes-graphics/gpu-viv-bin-s32v2xx/gpu-viv-bin-s32v2xx_6.4.0.bb:do_populate_lic) failed with exit code '1'

Issue: ALB-7472

Signed-off-by: Radu Pirea (NXP OSS) <radu-nicolae.pirea@oss.nxp.com>