pfe: fix yocto build error "pfe metadata is not deterministic"
Fix the following bitbake error:

ERROR: When reparsing
    sources/meta-alb/recipes-kernel/pfe/pfe_0.9.4.bb:do_populate_sysroot,
    the basehash value changed from
    311319889c8836cdf38a7e1445af8d4ab36899484d9f324bc4899eec2efd0a8b to
    9a4bf6fffee41f350bbe6f18be80985fe2a9ddb06aa673954b1ceca58a9e7d67.
    The metadata is not deterministic and this needs to be fixed.
    ERROR: The following commands may help:
    ERROR: $ bitbake pfe -cdo_populate_sysroot -Snone
    ERROR: Then:
    ERROR: $ bitbake pfe -cdo_populate_sysroot -Sprintdiff Full log can
    be found in attachment.

Issue: ALB-7223

Signed-off-by: Jan Petrous <jan.petrous@nxp.com>
Signed-off-by: Catalin Udma <catalin-dan.udma@nxp.com>