odp-module: add required include file for signal_pending
This commit fix the following error:
kern/kni_net.c:601:6: error: implicit declaration of function
'signal_pending

Issue: ALB-3946

Signed-off-by: Catalin Udma <catalin-dan.udma@nxp.com>