nxp-setup-alb.sh:qoriq: Layerscape targets fail to build
After running the script, building any recipe ends with error:
ERROR: Found duplicated BBFILE_COLLECTIONS 'security', check bblayers.conf or layer.conf to fix it.

This is due to a duplication of layer meta-security in the generated bblayers.conf file.

Issue: ALB-7634

Signed-off-by: Ionut Vicovan <Ionut.Vicovan@nxp.com>