secure-obj: Fix build error
The resipe as it comes from meta-freescale
does not build, it throws error:
"from Crypto.Signature import pss
 ImportError: cannot import name 'pss'
from 'Crypto.Signature'"
Issue comes from the fact that Crypto.Signature
does not exist in pycrypto, but rather in
pycryptodome.

Issue: ALB-5741

Signed-off-by: Ionut Vicovan <Ionut.Vicovan@nxp.com>