ubuntu: Update support for dunfell in nativeaptinstall.bbclass
Two issues are fixed here:
- yocto version is checked and this needs to be extended to dunfell
- an exception:
Exception: KeyError: 'getgrgid(): gid not found: 42'

Issue: ALB-6135

Signed-off-by: Heinz Wrobel <Heinz.Wrobel@nxp.com>
Signed-off-by: Ionut Vicovan <Ionut.Vicovan@nxp.com>