bazel: upgrade bazel to version 0.13.0 due to build error on 0.7.0
Bazel won't build on fsl-image-ubuntu when version 0.7.0 is used, with error

ERROR: /opt/bazel/bazel-0.7.0-dist/third_party/java/jarjar/BUILD:19:1: Building third_party/java/jarjar/libjarjar_core.jar (43 source files) failed (Exit 1): java failed: error executing command
  *(cd /tmp/bazel_aiyvuOnY/out/execroot/io_bazel && *
  *exec env - *
    *LC_CTYPE=en_US.UTF-8 *
  /usr/lib/jvm/java-8-oracle/bin/java -XX:+TieredCompilation '-XX:TieredStopAtLevel=1' -Xbootclasspath/p:third_party/java/jdk/langtools/javac-9-dev-r4023-3.jar -jar bazel-out/host/bin/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/bootstrap_deploy.jar @bazel-out/host/bin/third_party/java/jarjar/libjarjar_core.jar-2.params).
java.lang.InternalError: Cannot find requested resource bundle for locale en_US

When a new Ubuntu image is created, a newer openjdk-8-jdk version is installed
(javac 1.8.0_171) which have some incompatibility with bazel 0.7.0.

0.13.0-bazel build completed successfully

Issue: ALB-2611

Signed-off-by: Catalin Udma <catalin-dan.udma@nxp.com>