libgcc_7.3.0: fix libgcc 7.3.0 build for ls2* boards
When building libgcc, the following error occurs:
	error: #include nested too deeply
	|  #include <bits/floatn-64.h>
	|                             ^
	ERROR: Task
	(poky/meta/recipes-devtools/gcc/libgcc_7.3.bb:do_compile)
		failed with exit code '1'

The problem is added in the following commit in meta-qoriq-demos/sumo branch:
	commit d662d7d2dd33981aaedfc481b59fc1d946bbbd63
	Author: Chunrong Guo <chunrong.guo@nxp.com>
	Date:   Thu Mar 29 10:36:29 2018 +0800
	    glibc_2.27 : add bbappend

as it conflicts with poky/sumo after this commit was added:
	commit 88c43751319183dd7c3576d11bd5d83fb827a51c
	Author: Chen Qi <Qi.Chen@windriver.com>
	Date:   Fri Apr 20 17:07:34 2018 +0800
	    glibc: use oe_multilib_header on bits/floatn.h

The fix is to disable the conflicting commit in meta-qoriq-demo, by
disabling the corresponding bbappend for glibc.

Issue: ALB-3456

Signed-off-by: Catalin Udma <catalin-dan.udma@nxp.com>