secure-obj: Fix build error
The recipe as it comes from meta-freescale does not build, it throws error:
"from Crypto.Signature import pss
 ImportError: cannot import name 'pss'
from 'Crypto.Signature'"
Issue comes from the fact that Crypto.Signature
does not exist in pycrypto, but rather in pycryptodome.

PyCryptodome is "an almost drop-in replacement for the old PyCrypto library"
and installs under "Crypto" package. In cases when both PyCryptodome and old
PyCrypto are needed, there's PyCryptodomeX that installs under own name as
"Cryptodome" package.
The change has been performed in meta-openembedded
(commit 1fed24e60373866e13ceb12157575c4e09d5f261).

Issue: ALB-5741

Signed-off-by: Ionut Vicovan <Ionut.Vicovan@nxp.com>