glibc2.27: Fix build issues with gcc 10 (Ubuntu 18)
- Fix compile errors (force to treat them as warnings):
../csu/libc-tls.c:209:30: error: array subscript 1 is outside the bounds of an interior zero-length array 'struct dtv_slotinfo[0]' [-Werror=zero-length-bounds]
../inet/net-internal.h:88:7: error: 'total_deadline.absolute.tv_sec' may be used uninitialized in this function [-Werror=maybe-uninitialized]

- Fix yocto warnings:
NOTE: preferred version 2.27 of nativesdk-glibc not available (for item nativesdk-ldconfig)
NOTE: versions of nativesdk-glibc available: 2.32
NOTE: preferred version 2.27 of glibc not available (for item ldconfig)
NOTE: versions of glibc available: 2.32
./../include/xxx.h:yyy:zz: warning: 'sss' specifies less restrictive attribute than its target 'ttt': 'nothrow' [-Wmissing-attributes]
WARNING: xxx/sources/meta-alb/recipes-core/glibc2.27/glibc_2.27.bb: Recipe inherits features_check but doesn't use it

- Fix a multilib bug which corrupted wordsize.h and cause configure to fail

Issue: ALB-6317

Signed-off-by: Ionut Vicovan <Ionut.Vicovan@nxp.com>