ubuntu: fix python3 missing dependency for fsl-image-ubuntu
The following error is seen when building fsl-image-ubuntu

Problem: conflicting requests

nothing provides /usr/bin/python3 needed by
	kernel-devsrc-1.0-r0.s32v234bbmini
ERROR: fsl-image-ubuntu-1.0-r0 do_rootfs: Function failed: do_rootfs

The fix is to specifically set ubuntu-base as python3 provider and add
the missing /usr/bin/python3 symbolic link

Issue: ALB-2946

Signed-off-by: Catalin Udma <catalin-dan.udma@nxp.com>