ubuntu: overwrite VIRTUAL-RUNTIME for update-alternatives
Fix error
Error: Transaction test error:
    file /usr/bin/update-alternatives conflicts between attempted
    installs of update-alternatives-opkg-0.4.3-r0.aarch64 and
    ubuntu-base-20.04.1-r0.aarch64

Issue: ALB-6048

Signed-off-by: Catalin Udma <catalin-dan.udma@nxp.com>