ls2:ubuntu:atf: Fix dependencies and build target
Fix error:
ERROR: python3-3.8.2-r0 do_package_qa: QA Issue:
/usr/lib/python3.8/test/ziptestdata/header.sh contained in package
python3-tests requires /bin/bash, but no providers found in
RDEPENDS_python3-tests? [file-rdeps]

The source of this error is that dependencies from the atf recipe
used for LS2 are wrong.
The recipe mixes some native and target dependencies, including
openssl and python, which makes ubuntu builds using this component
to pull in packages which do not have dependencies met (as they
address a different environment)
Openssl is not even used during the build.

Issue: ALB-6612

Signed-off-by: Ionut Vicovan <Ionut.Vicovan@nxp.com>